# _data/organizations/great-lakes-environmental-research-laboratory.yml

name: Great Lakes Environmental Research Laboratory
slug: great-lakes-environmental-research-laboratory
abbreviation:
organization_type:   # Academic | Government | Military | NGO | Foundation | Commercial
parent_organization:
country:
address: |
  Lake Michigan Field Station
  1431 Beach St.
  Muskegon, MI 49441, USA
primary_contact:
phone: 231-759 5173 or 231-759 2314
fax: 231 759-2414
email: "Dennis.Donahue@noaa.gov"
url: "http://borris.glerl.noaa.gov/"
url_fleet:
record_updated:
notes:
