# _data/organizations/national-environmental-research-institute.yml

name: "National Environmental Research Institute,"
slug: national-environmental-research-institute
abbreviation:
organization_type:   # Academic | Government | Military | NGO | Foundation | Commercial
parent_organization:
country:
address: |
  Department of Marine Ecology,
  Frederiksborgvej 399, P.O. Box 358,
  DK-4000 Roskilde, Denmark
primary_contact:
phone: +45 4630 1200
fax: +45 4630 1114
email: "gae@dmu.dk"
url: 
url_fleet:
record_updated:
notes:
