# _data/organizations/us-environmental-protection-agency.yml

name: U.S. Environmental Protection Agency
slug: us-environmental-protection-agency
abbreviation:
organization_type:   # Academic | Government | Military | NGO | Foundation | Commercial
parent_organization:
country:
address: |
  U.S. Environmental Protection Agency, 6201 Congdon Bld,
  Duluth,  Minnesota, 55804
  USA
primary_contact:
phone: 218-529-5211
fax: 218-529-5003
email: "miller.samuel@epa.gov"
url: "http://www.epa.gov/"
url_fleet:
record_updated:
notes:
